minimumReleaseAge: 10080
minimumReleaseAgeIgnoreMissingTime: false
trustLockfile: false
strictDepBuilds: true
allowBuilds:
  esbuild: true
  fsevents: true
  sharp: true
  unrs-resolver: true
  workerd: set this to true or false
enableGlobalVirtualStore: false
packageImportMethod: clone-or-copy
verifyDepsBeforeRun: false
optimisticRepeatInstall: false
