// Generated from data.sql. Original identifiers and relationships are preserved.
import { sqliteTable, integer, text, numeric, index, uniqueIndex, foreignKey, check } from "drizzle-orm/sqlite-core";
import { sql } from "drizzle-orm";
export const CLUBS: any = sqliteTable("CLUBS", {
  club_id: integer("club_id").primaryKey({autoIncrement:true}),
  club_code: text("club_code").notNull(),
  club_name: text("club_name").notNull(),
  description: text("description"),
  founded_date: text("founded_date"),
  club_status: text("club_status").notNull(),
  created_at: text("created_at").notNull(),
}, (t) => [
  uniqueIndex("UQ_CLUBS_club_code").on(t.club_code),
  check("CK_CLUBS_club_status",sql`(${t.club_status}='INACTIVE' OR ${t.club_status}='ACTIVE')`),
]);
export const FINANCIAL_TRANSACTIONS: any = sqliteTable("FINANCIAL_TRANSACTIONS", {
  transaction_id: integer("transaction_id").primaryKey({autoIncrement:true}),
  club_id: integer("club_id").notNull(),
  event_id: integer("event_id"),
  category_id: integer("category_id").notNull(),
  related_member_id: integer("related_member_id"),
  transaction_type: text("transaction_type").notNull(),
  amount: numeric("amount").notNull(),
  transaction_date: text("transaction_date").notNull(),
  description: text("description").notNull(),
  evidence_url: text("evidence_url"),
  transaction_status: text("transaction_status").notNull(),
  created_by: integer("created_by").notNull(),
  approved_by: integer("approved_by"),
  created_at: text("created_at").notNull(),
  approved_at: text("approved_at"),
  rejection_reason: text("rejection_reason"),
}, (t) => [
  foreignKey({name:"FK_FINANCIAL_TRANSACTIONS_APPROVED_BY",columns:[t.approved_by],foreignColumns:[USERS.user_id]}),
  foreignKey({name:"FK_FINANCIAL_TRANSACTIONS_CATEGORY",columns:[t.category_id],foreignColumns:[FINANCE_CATEGORIES.category_id]}),
  foreignKey({name:"FK_FINANCIAL_TRANSACTIONS_CLUBS",columns:[t.club_id],foreignColumns:[CLUBS.club_id]}),
  foreignKey({name:"FK_FINANCIAL_TRANSACTIONS_CREATED_BY",columns:[t.created_by],foreignColumns:[USERS.user_id]}),
  foreignKey({name:"FK_FINANCIAL_TRANSACTIONS_EVENTS",columns:[t.event_id],foreignColumns:[EVENTS.event_id]}),
  foreignKey({name:"FK_FINANCIAL_TRANSACTIONS_MEMBER",columns:[t.related_member_id],foreignColumns:[CLUB_MEMBERS.club_member_id]}),
  index("IX_FT_club_date").on(t.club_id,t.transaction_date),
  index("IX_FT_status").on(t.transaction_status),
  check("CK_FINANCIAL_TRANSACTIONS_amount",sql`(${t.amount}>(0))`),
  check("CK_FINANCIAL_TRANSACTIONS_rejection_reason",sql`(${t.transaction_status}<>'REJECTED' OR nullif(ltrim(rtrim(${t.rejection_reason})),'') IS NOT NULL)`),
  check("CK_FINANCIAL_TRANSACTIONS_status",sql`(${t.transaction_status}='CANCELLED' OR ${t.transaction_status}='POSTED' OR ${t.transaction_status}='REJECTED' OR ${t.transaction_status}='APPROVED' OR ${t.transaction_status}='PENDING_APPROVAL' OR ${t.transaction_status}='DRAFT')`),
  check("CK_FINANCIAL_TRANSACTIONS_type",sql`(${t.transaction_type}='EXPENSE' OR ${t.transaction_type}='INCOME')`),
]);
export const EVENTS: any = sqliteTable("EVENTS", {
  event_id: integer("event_id").primaryKey({autoIncrement:true}),
  club_id: integer("club_id").notNull(),
  created_by: integer("created_by").notNull(),
  event_name: text("event_name").notNull(),
  event_type: text("event_type").notNull(),
  location: text("location").notNull(),
  start_at: text("start_at").notNull(),
  end_at: text("end_at").notNull(),
  registration_deadline: text("registration_deadline").notNull(),
  capacity: integer("capacity"),
  approval_required: integer("approval_required").notNull(),
  event_status: text("event_status").notNull(),
  attendance_locked: integer("attendance_locked").notNull(),
  created_at: text("created_at").notNull(),
  updated_at: text("updated_at"),
}, (t) => [
  foreignKey({name:"FK_EVENTS_CLUBS",columns:[t.club_id],foreignColumns:[CLUBS.club_id]}),
  foreignKey({name:"FK_EVENTS_CREATED_BY",columns:[t.created_by],foreignColumns:[USERS.user_id]}),
  index("IX_EVENTS_club_time").on(t.club_id,t.start_at),
  check("CK_EVENTS_capacity",sql`(${t.capacity} IS NULL OR ${t.capacity}>(0))`),
  check("CK_EVENTS_event_status",sql`(${t.event_status}='CANCELLED' OR ${t.event_status}='COMPLETED' OR ${t.event_status}='ONGOING' OR ${t.event_status}='CLOSED' OR ${t.event_status}='OPEN' OR ${t.event_status}='DRAFT')`),
  check("CK_EVENTS_registration_deadline",sql`(${t.registration_deadline}<=${t.start_at})`),
  check("CK_EVENTS_time",sql`(${t.end_at}>${t.start_at})`),
]);
export const EVENT_REGISTRATIONS: any = sqliteTable("EVENT_REGISTRATIONS", {
  registration_id: integer("registration_id").primaryKey({autoIncrement:true}),
  event_id: integer("event_id").notNull(),
  club_member_id: integer("club_member_id").notNull(),
  registration_status: text("registration_status").notNull(),
  registered_at: text("registered_at").notNull(),
  reviewed_by: integer("reviewed_by"),
  reviewed_at: text("reviewed_at"),
  cancelled_at: text("cancelled_at"),
}, (t) => [
  foreignKey({name:"FK_EVENT_REGISTRATIONS_EVENTS",columns:[t.event_id],foreignColumns:[EVENTS.event_id]}),
  foreignKey({name:"FK_EVENT_REGISTRATIONS_MEMBER",columns:[t.club_member_id],foreignColumns:[CLUB_MEMBERS.club_member_id]}),
  foreignKey({name:"FK_EVENT_REGISTRATIONS_REVIEWED_BY",columns:[t.reviewed_by],foreignColumns:[USERS.user_id]}),
  uniqueIndex("UQ_EVENT_REGISTRATIONS_event_member").on(t.event_id,t.club_member_id),
  index("IX_ER_event_status").on(t.event_id,t.registration_status),
  check("CK_EVENT_REGISTRATIONS_status",sql`(${t.registration_status}='CANCELLED' OR ${t.registration_status}='REJECTED' OR ${t.registration_status}='CONFIRMED' OR ${t.registration_status}='PENDING')`),
]);
export const ATTENDANCE: any = sqliteTable("ATTENDANCE", {
  attendance_id: integer("attendance_id").primaryKey({autoIncrement:true}),
  event_id: integer("event_id").notNull(),
  club_member_id: integer("club_member_id").notNull(),
  registration_id: integer("registration_id"),
  attendance_status: text("attendance_status").notNull(),
  check_in_at: text("check_in_at"),
  recorded_by: integer("recorded_by").notNull(),
  recorded_at: text("recorded_at").notNull(),
}, (t) => [
  foreignKey({name:"FK_ATTENDANCE_EVENTS",columns:[t.event_id],foreignColumns:[EVENTS.event_id]}),
  foreignKey({name:"FK_ATTENDANCE_MEMBER",columns:[t.club_member_id],foreignColumns:[CLUB_MEMBERS.club_member_id]}),
  foreignKey({name:"FK_ATTENDANCE_RECORDED_BY",columns:[t.recorded_by],foreignColumns:[USERS.user_id]}),
  foreignKey({name:"FK_ATTENDANCE_REGISTRATION",columns:[t.registration_id],foreignColumns:[EVENT_REGISTRATIONS.registration_id]}),
  uniqueIndex("UQ_ATTENDANCE_event_member").on(t.event_id,t.club_member_id),
  index("IX_ATT_event_status").on(t.event_id,t.attendance_status),
  check("CK_ATTENDANCE_status",sql`(${t.attendance_status}='EXCUSED' OR ${t.attendance_status}='LATE' OR ${t.attendance_status}='ABSENT' OR ${t.attendance_status}='PRESENT')`),
]);
export const AUDIT_LOGS: any = sqliteTable("AUDIT_LOGS", {
  audit_id: integer("audit_id").primaryKey({autoIncrement:true}),
  user_id: integer("user_id"),
  club_id: integer("club_id"),
  action_code: text("action_code").notNull(),
  entity_name: text("entity_name").notNull(),
  entity_id: text("entity_id"),
  old_value: text("old_value"),
  new_value: text("new_value"),
  created_at: text("created_at").notNull(),
}, (t) => [
  foreignKey({name:"FK_AUDIT_LOGS_CLUBS",columns:[t.club_id],foreignColumns:[CLUBS.club_id]}),
  foreignKey({name:"FK_AUDIT_LOGS_USERS",columns:[t.user_id],foreignColumns:[USERS.user_id]}),
  index("IX_AL_entity").on(t.entity_name,t.entity_id),
  check("CK_AUDIT_LOGS_new_value_json",sql`(${t.new_value} IS NULL OR json_valid(${t.new_value})=(1))`),
  check("CK_AUDIT_LOGS_old_value_json",sql`(${t.old_value} IS NULL OR json_valid(${t.old_value})=(1))`),
]);
export const CLUB_MEMBERS: any = sqliteTable("CLUB_MEMBERS", {
  club_member_id: integer("club_member_id").primaryKey({autoIncrement:true}),
  club_id: integer("club_id").notNull(),
  user_id: integer("user_id").notNull(),
  member_code: text("member_code").notNull(),
  join_date: text("join_date").notNull(),
  leave_date: text("leave_date"),
  member_status: text("member_status").notNull(),
  department_name: text("department_name"),
  position_name: text("position_name"),
  created_at: text("created_at").notNull(),
  updated_at: text("updated_at"),
}, (t) => [
  foreignKey({name:"FK_CLUB_MEMBERS_CLUBS",columns:[t.club_id],foreignColumns:[CLUBS.club_id]}),
  foreignKey({name:"FK_CLUB_MEMBERS_USERS",columns:[t.user_id],foreignColumns:[USERS.user_id]}),
  uniqueIndex("UQ_CLUB_MEMBERS_club_member_code").on(t.club_id,t.member_code),
  uniqueIndex("UQ_CLUB_MEMBERS_club_user").on(t.club_id,t.user_id),
  index("IX_CM_club_status").on(t.club_id,t.member_status),
  check("CK_CLUB_MEMBERS_leave_date",sql`(${t.leave_date} IS NULL OR ${t.leave_date}>=${t.join_date})`),
  check("CK_CLUB_MEMBERS_member_status",sql`(${t.member_status}='LEFT' OR ${t.member_status}='PAUSED' OR ${t.member_status}='ACTIVE')`),
]);
export const FINANCE_CATEGORIES: any = sqliteTable("FINANCE_CATEGORIES", {
  category_id: integer("category_id").primaryKey({autoIncrement:true}),
  club_id: integer("club_id").notNull(),
  category_type: text("category_type").notNull(),
  category_name: text("category_name").notNull(),
  active_flag: integer("active_flag").notNull(),
}, (t) => [
  foreignKey({name:"FK_FINANCE_CATEGORIES_CLUBS",columns:[t.club_id],foreignColumns:[CLUBS.club_id]}),
  uniqueIndex("UQ_FINANCE_CATEGORIES").on(t.club_id,t.category_type,t.category_name),
  check("CK_FINANCE_CATEGORIES_type",sql`(${t.category_type}='EXPENSE' OR ${t.category_type}='INCOME')`),
]);
export const MEMBER_STATUS_HISTORY: any = sqliteTable("MEMBER_STATUS_HISTORY", {
  history_id: integer("history_id").primaryKey({autoIncrement:true}),
  club_member_id: integer("club_member_id").notNull(),
  old_status: text("old_status"),
  new_status: text("new_status").notNull(),
  reason: text("reason"),
  changed_by: integer("changed_by").notNull(),
  changed_at: text("changed_at").notNull(),
}, (t) => [
  foreignKey({name:"FK_MEMBER_STATUS_HISTORY_CHANGED_BY",columns:[t.changed_by],foreignColumns:[USERS.user_id]}),
  foreignKey({name:"FK_MEMBER_STATUS_HISTORY_MEMBER",columns:[t.club_member_id],foreignColumns:[CLUB_MEMBERS.club_member_id]}),
  check("CK_MEMBER_STATUS_HISTORY_new_status",sql`(${t.new_status}='LEFT' OR ${t.new_status}='PAUSED' OR ${t.new_status}='ACTIVE')`),
  check("CK_MEMBER_STATUS_HISTORY_old_status",sql`(${t.old_status} IS NULL OR (${t.old_status}='LEFT' OR ${t.old_status}='PAUSED' OR ${t.old_status}='ACTIVE'))`),
]);
export const ROLES: any = sqliteTable("ROLES", {
  role_id: integer("role_id").primaryKey({autoIncrement:true}),
  role_code: text("role_code").notNull(),
  role_name: text("role_name").notNull(),
}, (t) => [
  uniqueIndex("UQ_ROLES_role_code").on(t.role_code),
  check("CK_ROLES_role_code",sql`(${t.role_code}='MEMBER' OR ${t.role_code}='TREASURER' OR ${t.role_code}='OFFICER' OR ${t.role_code}='LEADER' OR ${t.role_code}='ADMIN')`),
]);
export const USER_ROLES: any = sqliteTable("USER_ROLES", {
  user_role_id: integer("user_role_id").primaryKey({autoIncrement:true}),
  user_id: integer("user_id").notNull(),
  role_id: integer("role_id").notNull(),
  club_id: integer("club_id"),
  assigned_by: integer("assigned_by"),
  assigned_at: text("assigned_at").notNull(),
  active_flag: integer("active_flag").notNull(),
}, (t) => [
  foreignKey({name:"FK_USER_ROLES_ASSIGNED_BY",columns:[t.assigned_by],foreignColumns:[USERS.user_id]}),
  foreignKey({name:"FK_USER_ROLES_CLUBS",columns:[t.club_id],foreignColumns:[CLUBS.club_id]}),
  foreignKey({name:"FK_USER_ROLES_ROLES",columns:[t.role_id],foreignColumns:[ROLES.role_id]}),
  foreignKey({name:"FK_USER_ROLES_USERS",columns:[t.user_id],foreignColumns:[USERS.user_id]}),
  uniqueIndex("UQ_USER_ROLES_scope").on(t.user_id,t.role_id,t.club_id),
  index("IX_USER_ROLES_user_club_active").on(t.user_id,t.club_id,t.active_flag),
]);
export const USERS: any = sqliteTable("USERS", {
  user_id: integer("user_id").primaryKey({autoIncrement:true}),
  student_code: text("student_code"),
  username: text("username").notNull(),
  password_hash: text("password_hash").notNull(),
  full_name: text("full_name").notNull(),
  email: text("email"),
  phone: text("phone"),
  faculty: text("faculty"),
  class_name: text("class_name"),
  account_status: text("account_status").notNull(),
  created_at: text("created_at").notNull(),
  updated_at: text("updated_at"),
}, (t) => [
  uniqueIndex("UQ_USERS_username").on(t.username),
  uniqueIndex("UX_USERS_email").on(t.email),
  uniqueIndex("UX_USERS_student_code").on(t.student_code),
  check("CK_USERS_account_status",sql`(${t.account_status}='INACTIVE' OR ${t.account_status}='LOCKED' OR ${t.account_status}='ACTIVE')`),
]);
export const AUTH_SESSIONS = sqliteTable("AUTH_SESSIONS", { token_hash:text().primaryKey(), user_id:integer().notNull().references(()=>USERS.user_id), expires_at:integer().notNull(), created_at:text().notNull() });
export const AUTH_ATTEMPTS = sqliteTable("AUTH_ATTEMPTS", { attempt_id:integer().primaryKey({autoIncrement:true}), identifier:text().notNull(), attempted_at:integer().notNull() },t=>[index("IX_AUTH_ATTEMPTS_identifier_time").on(t.identifier,t.attempted_at)]);
export const APP_SETUP = sqliteTable("APP_SETUP", { setup_id:integer().primaryKey(), completed_at:text().notNull() });
export const CLUB_JOIN_REQUESTS = sqliteTable("CLUB_JOIN_REQUESTS", {
  request_id: integer().primaryKey({ autoIncrement: true }),
  club_id: integer().notNull().references(() => CLUBS.club_id),
  user_id: integer().notNull().references(() => USERS.user_id),
  request_status: text().notNull().default("PENDING"),
  message: text(),
  review_note: text(),
  created_at: text().notNull(),
  reviewed_by: integer().references(() => USERS.user_id),
  reviewed_at: text(),
}, (t) => [
  uniqueIndex("UQ_CLUB_JOIN_REQUESTS_club_user").on(t.club_id, t.user_id),
  index("IX_CLUB_JOIN_REQUESTS_status").on(t.club_id, t.request_status),
  check("CK_CLUB_JOIN_REQUESTS_status", sql`${t.request_status} IN ('PENDING','APPROVED','REJECTED')`),
]);
